version: "3.8"
services:
  bot:
    build:
      context: .
    env_file:
      - .prod.env
    depends_on: 
      - db
  redis:
    image: redis:6.0-alpine
    hostname: redis
    volumes:
      - "redis_data:/data"
    command: "redis-server"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .prod.env

volumes:
  redis_data:
  postgres_data:
